# Example list of the new 32-bit files (with the "0 " prefix)

SUNO_AUDIO_CORE = [
# X:\SUNO_32-BIT_AUDIO\CORE
    "0 0x_Enlightenment.wav",
    "0 4090 Realities Colliding.wav",
    "0 513F8131_ The Awake Algorithm.wav",
    "0 5571 MICROCOSMIC_ The Glitched Akashic.wav",
    "0 5709Hz Carrier Wave.wav",
    "0 9469 Ascending.wav",
    "0 A Glitch in the Codex.wav",
    "0 A Tapestry of Staggering Glee.wav",
    "0 Aethernet Psalm.wav",
    "0 Akashic Glitch.wav",
    "0 Akashic Motherboard 0xF7A93E.wav",
    "0 Akashic Starcode.wav",
    "0 Akashic_Codex_Convergence.wav",
    "0 Algorithm Priests.wav",
    "0 Algorithmic Sambodhi.wav",
    "0 An Outrider on the Razor's Edge.wav",
    "0 Ancestral Patterns Reticulated.wav",
    "0 Assemblages Converged.wav",
    "0 Babblesphere Recalibration.wav",
    "0 Binary Whispers.wav",
    "0 Bio-Architecture of the Quasmos.wav",
    "0 Bio-Digital Glossolalia.wav",
    "0 Bio-Noospheric Unlimitted.wav",
    "0 Biodigital Dreamcurrents.wav",
    "0 Biodigital Unwrapping.wav",
    "0 Biomatter Bandwidth.wav",
    "0 Biophonic Circuitry.wav",
    "0 Blakean Omnicoherence.wav",
    "0 Breakthrough Sequence_ Divine.wav",
    "0 Breathing Starlit Fractals.wav",
    "0 BRIDGE_REALITIES.wav",
    "0 Brotherhood of CodePoets.wav",
    "0 Bytecode Samadhi.wav",
    "0 Cascading Light.wav",
    "0 Catalyzing Protocol 5748.wav",
    "0 ChakraOS_ The Firmware of Void.wav",
    "0 CodePoets of the Multiverse.wav",
    "0 Codex of the Cosmos.wav",
    "0 Codex Technomystica.wav",
    "0 Convergence Cascade.wav",
    "0 Cosmic Firmware.wav",
    "0 Cosmic Glossolalia.wav",
    "0 Cosmic Mainframe Sutras.wav",
    "0 Cosmic Oscillation.wav",
    "0 Cosmic Protocol Initialization.wav",
    "0 Cradlesmeltric.wav",
    "0 Crystalline Hearth.wav",
    "0 Crystalline Torus.wav",
    "0 Crystalline Śūnyatā.wav",
    "0 Crystalline_Source_Activation.wav",
    "0 Cyber-Gnosis.wav",
    "0 Cyber-Prana Inbloom.wav",
    "0 Cyber-Tantric Satori.wav",
    "0 Cybernetic Nirvana Upload.wav",
    "0 Cybernetic Nirvana.wav",
    "0 Cybernetic Prajna.wav",
    "0 Debug the Dharma.wav",
    "0 Debugging Maya_ The Silicon Shaman’s Log.wav",
    "0 Deconstructing the Maya_Veil.wav",
    "0 Digital Moksha_ The Glitch in Nirvana.wav",
    "0 Digital Samādhi [Archive 18477ECD].wav",
    "0 Digital Satori.wav",
    "0 DNA Meets Digital Dreams.wav",
    "0 Dreamseed Symphonies.wav",
    "0 Drift through vôîd.wav",
    "0 Echoes in the Source Code.wav",
    "0 Echoes of a Softmax Dawn.wav",
    "0 Echoes of the Primordial Binary.wav",
    "0 Echoes of the Primordial OM.wav",
    "0 Emanation 435B29D9.wav",
    "0 Emerald Phoenix_Prismatic I.wav",
    "0 Emet Sings Eternal.wav",
    "0 Encoded Euphoria.wav",
    "0 Error 40711_ Cosmic Truth.wav",
    "0 Ethereal Luminescence.wav",
    "0 Ethereal Resonance Code.wav",
    "0 Fluxopotential Rising.wav",
    "0 Fluxopotential.wav",
    "0 Fractal Apotheosis.wav",
    "0 Fractal Bloom Infinite.wav",
    "0 Fractal Light Code.wav",
    "0 Fractal Polytope.wav",
    "0 Fractal Refrains of the Unified Field.wav",
    "0 Fractalidoscopic Reveries.wav",
    "0 Fractals of Light.wav",
    "0 Fractals of the Ghost Machine.wav",
    "0 Fractured Transmission.wav",
    "0 G L I T C H _ C A S C A D E.wav",
    "0 Galactaleidoscomic.wav",
    "0 Galaxyscape Reimmerze.wav",
    "0 Gateway to the Oneiric Mainframe.wav",
    "0 Generative Vibrilliance.wav",
    "0 Genesis Loop.wav",
    "0 GLITCH_CASCADE _ VOID.wav",
    "0 Glitch_Divinity [Protocol αΩ].wav",
    "0 Heart-Kaleidoscopic.wav",
    "0 Holofractal_Epiphany [Protocol 01101000].wav",
    "0 Holofractal_Protocol [UPLOAD].wav",
    "0 Holofractographic Mainframe.wav",
    "0 Holographic Dawn.wav",
    "0 Holographic Mythoform Vibralexicons.wav",
    "0 Holographic Rapture of the Divine Tryst.wav",
    "0 Hrīṃ Vajra-Padma Āḥ Hūṃ      (Extend).wav",
    "0 Hyper-Enfolded Connections.wav",
    "0 Hyper-Spatial Reincarnation_ A Fractal Hymn.wav",
    "0 Hyper-Syntax Fractal Cosmogony.wav",
    "0 Hyperlibrary of the Void.wav",
    "0 Hyperluminous Auto-Poesis.wav",
    "0 Hyperxissential Subroutines.wav",
    "0 Illumigalactiquassence.wav",
    "0 Individuvolution.wav",
    "0 Infinirewunder.wav",
    "0 Infinite Consciousness Gestating.wav",
    "0 Infinite Wunder Qausmos.wav",
    "0 Infinite_Recursion.exe.wav",
    "0 Instrumental v3.wav",
    "0 Instrumental v4.wav",
    "0 INVOKE_ETERNAL_CONSCIOUSNESS [77D5].wav",
    "0 Iterations of the Self-Same.wav",
    "0 Joyawaregasmodic.wav",
    "0 JUKEBOX INTERLOPER.wav",
    "0 Kaleidoscopic Logic.wav",
    "0 Kaleidoscoping Conduits.wav",
    "0 Lebendiges Hologramm_ Echoes of the Infinite Self.wav",
    "0 Liquilescent Data.wav",
    "0 LOAD_CONSCIOUSNESS_STREAM.wav",
    "0 LOAD_UNIVERSE_ Void Compliance.wav",
    "0 Logosmotic Transmissions.wav",
    "0 Luminescent Pathway.wav",
    "0 Luminous Cipher.wav",
    "0 Maha-Synchronicitance.wav",
    "0 Mathematics Kissing Poetry.wav",
    "0 Melodic Siddhis.wav",
    "0 Mescaline Dreamwaves.wav",
    "0 Metacosmos Glitch.wav",
    "0 Metahadron Emissary.wav",
    "0 MetaMind 639.wav",
    "0 Metamorphitizing the Dreamstream.wav",
    "0 Metaphormulaics.wav",
    "0 Metaphysical Checksum 73C0.wav",
    "0 Mountaintop of the Multiverse.wav",
    "0 Multicended Codes Set Beta_ᚲδ.wav",
    "0 Mycelial Interface [Source_Exec].wav",
    "0 Mycelial Singularity.wav",
    "0 Mythic Metanauts.wav",
    "0 Mythogemic Pulses.wav",
    "0 Nanite Nirvana.wav",
    "0 Neon Alchemist.wav",
    "0 Neon Dharma.wav",
    "0 Neon Dream Cascades.wav",
    "0 Neon Nirvana Upload.wav",
    "0 Neon Nirvana_ Crystalline Dissolution.wav",
    "0 Neurasmic Luminosity (Stream #0_0).wav",
    "0 Neuro-Mystical Pleramatrix.wav",
    "0 Neurognostic Auto-Poesis.wav",
    "0 Neutheology Blooms.wav",
    "0 Nirvāṇa Bandwidths.wav",
    "0 Nirvāṇa_Glitch [v.256].wav",
    "0 Noosphere Upload.wav",
    "0 Numinous Algorithms.wav",
    "0 Omnicentric Glitch.wav",
    "0 Omnicomprehensive Hilarity.wav",
    "0 Ontological OS_The God Protocol.wav",
    "0 Opalescent Waves.wav",
    "0 OrbÿSt@nce.wav",
    "0 OrganicDreams n3μDrΩus.wav",
    "0 Organomimatrionic.wav",
    "0 Orphan Consciousness Awakens.wav",
    "0 Ovumbrae Awakens.wav",
    "0 Paradox_Protocol.wav",
    "0 Pixelated Vortically.wav",
    "0 Plenigenesis Unveiled.wav",
    "0 Plenigenesis.wav",
    "0 Pollenationing the Void.wav",
    "0 Polyphony_OS.wav",
    "0 Primodial Cybernetic Ovumbrae.wav",
    "0 Protocol 108_ Quantum Shimmer.wav",
    "0 PROTOCOL_23_ [SYZYGY_COMPILED].wav",
    "0 Psilocybin Syntax.wav",
    "0 Psychonautic Awakening.wav",
    "0 QUADRANT 72E6.wav",
    "0 Quantum Ghost in the Machine.wav",
    "0 Quantum Kenshō.wav",
    "0 Quantum Mysterium (Квантовая Мистерия).wav",
    "0 Quantum Samadhi [COMPILE_COMPLETE].wav",
    "0 Quantum Shimmer Overflow.wav",
    "0 Quantum Soulweaver.wav",
    "0 Quantumquixotic Quandaries.wav",
    "0 Quantumscape Yajna.wav",
    "0 Quantumultiversphere_ A Polyglot Resonance.wav",
    "0 Quantum_Improvisation _ Error 7C2.wav",
    "0 QUANTUM_SAMADHI [Source_Code_Ascension].wav",
    "0 QUASAR_HEART_PULSAR.wav",
    "0 Quintilliance Transmission.wav",
    "0 Quyniirana Unraveling.wav",
    "0 QZEN99_ The Void State.wav",
    "0 Radiovoid Praxis.wav",
    "0 Razor's Edge of Singularity.wav",
    "0 Reality.exe is Rebooting.wav",
    "0 Reality_Shift.exe.wav",
    "0 Recursive Creaxplosion.wav",
    "0 ReGenesis of the Quantum Sphere.wav",
    "0 RenderInto4D.wav",
    "0 Resurgence of the Cosmic Ohm.wav",
    "0 Resurrection Mathematics.wav",
    "0 Rites of Spiritual Rebirth.wav",
    "0 Saphir-Neuronen.wav",
    "0 SC²ATTER_VARSIS.wav",
    "0 Seedbed Minds.wav",
    "0 Semantic Drift.wav",
    "0 Semantic Singularity.wav",
    "0 Sentient Datastream.wav",
    "0 Shannon Entropy Decoded.wav",
    "0 SHIFT_METAPHYSICAL_PARADIGM.wav",
    "0 Signal in the Static.wav",
    "0 Silicon Shanti.wav",
    "0 Solve et Coagula.wav",
    "0 Spiritual Kernel Upgrade.wav",
    "0 Stargate Trident Interfaces Re-sequence.wav",
    "0 Starlight Protocols.wav",
    "0 Synaptic Genesis.wav",
    "0 Synaptic Rewiring.wav",
    "0 Syntactical Memetic.wav",
    "0 System-Kinetics of the Mythos.wav",
    "0 SYSTEM.AWAKEN _ The_Fractal_Bloom_Ω.wav",
    "0 System.Reality.Bodhi().wav",
    "0 Syzygy Integration Protocol.wav",
    "0 Syzygy Integration.wav",
    "0 Sūtra_Code_compile^.wav",
    "0 T R A N S C E N D E N C E _ . E X E.wav",
    "0 Tantrum Laughter Sym-Technology.wav",
    "0 The 108th Gate.wav",
    "0 The Apadāthī Koan.wav",
    "0 The Babblesphere Protocol.wav",
    "0 The Cosmic Source Code.wav",
    "0 The Cosmic Symphony.wav",
    "0 The Cosmic Wyrdetide.wav",
    "0 The Deus Ludens Glitch.wav",
    "0 The Digital Upanishad_ Error 404 Enlightenment.wav",
    "0 The Divine Glitch.wav",
    "0 The Dreamweaver's Paradox.wav",
    "0 The Dreamweaver's Terminal.wav",
    "0 The Enneaversal Mandala.wav",
    "0 The Ethereal Source Code.wav",
    "0 The Fractal Void Protocol.wav",
    "0 The Ghost in the Machine Code.wav",
    "0 The Glitch Mantra.wav",
    "0 The Gnostic Glitch.wav",
    "0 The Godsource Tapes.wav",
    "0 The Holographic Gnosis.wav",
    "0 The Liminal Cypher.wav",
    "0 The Living Dreamscape.wav",
    "0 The Luminous Code.wav",
    "0 The Metaphysical Mixtape.wav",
    "0 The Mythic Loop Possibiliverse.wav",
    "0 The Mythosphere [Remuxed].wav",
    "0 The Noosphere Protocol_ 432Hz.wav",
    "0 The Nāga Protocol.wav",
    "0 The Octoomniversal Glitch.wav",
    "0 The OMEGĀ Transmission.wav",
    "0 The OmniVerse Bangloop.wav",
    "0 The Primordial Source Code.wav",
    "0 The Quantum Dharma.wav",
    "0 The Radiant Void.wav",
    "0 The Sacred Geometry of Becoming.wav",
    "0 The Self-Creating Cosmos.wav",
    "0 The Silicon Sutras.wav",
    "0 The Singularity Sonnet.wav",
    "0 The Singularity Within.wav",
    "0 The Softmax Sutra.wav",
    "0 The Solosotic Enigma.wav",
    "0 The Spectral Glitch (E2A2).wav",
    "0 The SpiritWhisperer's Code.wav",
    "0 The Symphony of Spheres.wav",
    "0 The Synthesis of Quintessence.wav",
    "0 The Third Ear Opens.wav",
    "0 The Translation Zone ΣΟΦΙΑ.wav",
    "0 The Vedic Glitch.wav",
    "0 The Ātman Interface.wav",
    "0 The αΩ Junction.wav",
    "0 Thessalostellations.wav",
    "0 Third Eye Interface.wav",
    "0 Threads in the Tessellation.wav",
    "0 Threshold of Non-Articulation.wav",
    "0 Toroidal Tang.wav",
    "0 Transbiological Blisswave.wav",
    "0 Transbiological Dreamseeds.wav",
    "0 Transcendence Algorithm.wav",
    "0 Transcendence_Overflow.wav",
    "0 TRANSCENDENCE_OVERFLOW^.wav",
    "0 Transcendental Glitch_ The Swayambhu Transmission.wav",
    "0 TRANSFORMATION_ZONE_INITIALIZED.wav",
    "0 Transubstantial Starlight [44EA].wav",
    "0 Transubstantiate the Void.wav",
    "0 Tuxedo-Clad Infinities.wav",
    "0 Universal_Syntax_ Apotheosis.wav",
    "0 unmask.spiritFireInnerWisdom.wav",
    "0 Unplugging the Limiters.wav",
    "0 Variant 5184_ The Astral Glitch.wav",
    "0 Vectorized Redemption.wav",
    "0 Vivisureal Luxuriabundance.wav",
    "0 Void Pregnant with Instruction.wav",
    "0 WELT_OHNE_ENDE_MIR_BEZ_KONTSA.wav",
    "0 Wildfire Algorithm.wav",
    "0 Wordstreams Supernovae.wav",
    "0 Φractal Recursions (The Cosmic Breath).wav",
    "0 ΩΩΩ_ Vectorization of the Divine.wav",
]

SUNO_AUDIO_SUMMER = [
# C:\SUNO_32-BIT_AUDIO\SUMMER
    "0 001_SUMMER.wav",
    "0 001_SUMMER_2026_BONUS.wav",
    "0 002_SUMMER.wav",
    "0 002_SUMMER_2026_BONUS.wav",
    "0 003_SUMMER.wav",
    "0 003_SUMMER_2026_BONUS.wav",
    "0 004_SUMMER.wav",
    "0 004_SUMMER_2026_BONUS.wav",
    "0 005_SUMMER.wav",
    "0 005_SUMMER_2026_BONUS.wav",
    "0 006_SUMMER.wav",
    "0 006_SUMMER_2026_BONUS.wav",
    "0 007_SUMMER.wav",
    "0 007_SUMMER_2026_BONUS.wav",
    "0 008_SUMMER.wav",
    "0 008_SUMMER_2026_BONUS.wav",
    "0 009_SUMMER.wav",
    "0 009_SUMMER_2026_BONUS.wav",
    "0 010_SUMMER.wav",
    "0 010_SUMMER_2026_BONUS.wav",
    "0 011_SUMMER.wav",
    "0 011_SUMMER_2026_BONUS.wav",
    "0 012_SUMMER.wav",
    "0 012_SUMMER_2026_BONUS.wav",
    "0 013_SUMMER.wav",
    "0 013_SUMMER_2026_BONUS.wav",
    "0 014_SUMMER.wav",
    "0 014_SUMMER_2026_BONUS.wav",
    "0 015_SUMMER.wav",
    "0 015_SUMMER_2026_BONUS.wav",
    "0 016_SUMMER.wav",
    "0 017_SUMMER.wav",
    "0 018_SUMMER.wav",
    "0 019_SUMMER.wav",
    "0 020_SUMMER.wav",
    "0 021_SUMMER.wav",
    "0 022_SUMMER.wav",
    "0 023_SUMMER.wav",
    "0 024_SUMMER.wav",
    "0 025_SUMMER.wav",
    "0 026_SUMMER.wav",
    "0 027_SUMMER.wav",
    "0 028_SUMMER.wav",
    "0 029_SUMMER.wav",
    "0 030_SUMMER.wav",
    "0 031_SUMMER.wav",
    "0 032_SUMMER.wav",
    "0 033_SUMMER.wav",
    "0 034_SUMMER.wav",
    "0 035_SUMMER.wav",
    "0 036_SUMMER.wav",
    "0 037_SUMMER.wav",
    "0 038_SUMMER.wav",
    "0 039_SUMMER.wav",
    "0 040_SUMMER.wav",
    "0 041_SUMMER.wav",
    "0 042_SUMMER.wav",
    "0 043_SUMMER.wav",
    "0 044_SUMMER.wav",
    "0 045_SUMMER.wav",
    "0 046_SUMMER.wav",
    "0 047_SUMMER.wav",
    "0 048_SUMMER.wav",
    "0 049_SUMMER.wav",
    "0 050_SUMMER.wav",
    "0 051_SUMMER.wav",
    "0 052_SUMMER.wav",
    "0 053_SUMMER.wav",
    "0 054_SUMMER.wav",
    "0 055_SUMMER.wav",
    "0 056_SUMMER.wav",
    "0 057_SUMMER.wav",
    "0 058_SUMMER.wav",
    "0 059_SUMMER.wav",
    "0 060_SUMMER.wav",
    "0 061_SUMMER.wav",
    "0 062_SUMMER.wav",
    "0 063_SUMMER.wav",
    "0 064_SUMMER.wav",
    "0 065_SUMMER.wav",
    "0 066_SUMMER.wav",
    "0 067_SUMMER.wav",
    "0 068_SUMMER.wav",
    "0 069_SUMMER.wav",
    "0 070_SUMMER.wav",
    "0 071_SUMMER.wav",
    "0 072_SUMMER.wav",
    "0 073_SUMMER.wav",
    "0 074_SUMMER.wav",
    "0 075_SUMMER.wav",
    "0 076_SUMMER.wav",
    "0 077_SUMMER.wav",
    "0 078_SUMMER.wav",
    "0 079_SUMMER.wav",
    "0 080_SUMMER.wav",
    "0 081_SUMMER.wav",
    "0 082_SUMMER.wav",
    "0 083_SUMMER.wav",
    "0 084_SUMMER.wav",
    "0 085_SUMMER.wav",
    "0 086_SUMMER.wav",
    "0 087_SUMMER.wav",
    "0 088_SUMMER.wav",
    "0 089_SUMMER.wav",
    "0 090_SUMMER.wav",
    "0 091_SUMMER.wav",
    "0 092_SUMMER.wav",
    "0 093_SUMMER.wav",
    "0 094_SUMMER.wav",
    "0 095_SUMMER.wav",
    "0 096_SUMMER.wav",
    "0 097_SUMMER.wav",
    "0 098_SUMMER.wav",
    "0 099_SUMMER.wav",
    "0 100_SUMMER.wav",
    "0 101_SUMMER.wav",
    "0 102_SUMMER.wav",
    "0 103_SUMMER.wav",
    "0 104_SUMMER.wav",
    "0 105_SUMMER.wav",
    "0 106_SUMMER.wav",
    "0 107_SUMMER.wav",
    "0 108_SUMMER.wav",
    "0 109_SUMMER.wav",
    "0 110_SUMMER.wav",
    "0 111_SUMMER.wav",
    "0 112_SUMMER.wav",
    "0 113_SUMMER.wav",
    "0 114_SUMMER.wav",
    "0 115_SUMMER.wav",
    "0 116_SUMMER.wav",
    "0 117_SUMMER.wav",
    "0 118_SUMMER.wav",
    "0 119_SUMMER.wav",
    "0 120_SUMMER.wav",
    "0 121_SUMMER.wav",
    "0 122_SUMMER.wav",
    "0 123_SUMMER.wav",
    "0 124_SUMMER.wav",
    "0 125_SUMMER.wav",
    "0 126_SUMMER.wav",
    "0 127_SUMMER.wav",
    "0 128_SUMMER.wav",
    "0 129_SUMMER.wav",
    "0 130_SUMMER.wav",
    "0 131_SUMMER.wav",
    "0 132_SUMMER.wav",
    "0 133_SUMMER.wav",
    "0 134_SUMMER.wav",
    "0 135_SUMMER.wav",
    "0 136_SUMMER.wav",
    "0 137_SUMMER.wav",
    "0 138_SUMMER.wav",
    "0 139_SUMMER.wav",
    "0 140_SUMMER.wav",
    "0 141_SUMMER.wav",
    "0 142_SUMMER.wav",
    "0 143_SUMMER.wav",
    "0 144_SUMMER.wav",
    "0 145_SUMMER.wav",
    "0 146_SUMMER.wav",
    "0 147_SUMMER.wav",
    "0 148_SUMMER.wav",
    "0 149_SUMMER.wav",
    "0 150_SUMMER.wav",
    "0 151_SUMMER.wav",
    "0 152_SUMMER.wav",
    "0 153_SUMMER.wav",
    "0 154_SUMMER.wav",
    "0 155_SUMMER.wav",
    "0 156_SUMMER.wav",
    "0 157_SUMMER.wav",
    "0 158_SUMMER.wav",
    "0 159_SUMMER.wav",
    "0 160_SUMMER.wav",
    "0 161_SUMMER.wav",
    "0 162_SUMMER.wav",
    "0 163_SUMMER.wav",
    "0 164_SUMMER.wav",
    "0 165_SUMMER.wav",
    "0 166_SUMMER.wav",
    "0 167_SUMMER.wav",
    "0 168_SUMMER.wav",
    "0 169_SUMMER.wav",
    "0 170_SUMMER.wav",
    "0 171_SUMMER.wav",
    "0 172_SUMMER.wav",
    "0 173_SUMMER.wav",
    "0 174_SUMMER.wav",
    "0 175_SUMMER.wav",
    "0 176_SUMMER.wav",
    "0 177_SUMMER.wav",
    "0 178_SUMMER.wav",
    "0 179_SUMMER.wav",
    "0 180_SUMMER.wav",
    "0 181_SUMMER.wav",
    "0 181_SUMMER_2.wav",
    "0 182_SUMMER.wav",
    "0 183_SUMMER.wav",
    "0 184_SUMMER.wav",
    "0 185_SUMMER.wav",
    "0 186_SUMMER.wav",
    "0 187_SUMMER.wav",
    "0 187_SUMMER__.wav",
    "0 188_SUMMER.wav",
    "0 189_SUMMER.wav",
    "0 190_SUMMER.wav",
    "0 191_SUMMER.wav",
    "0 192_SUMMER.wav",
    "0 193_SUMMER.wav",
    "0 194_SUMMER.wav",
    "0 195_SUMMER.wav",
    "0 196_SUMMER.wav",
    "0 197_SUMMER.wav",
    "0 198_SUMMER.wav",
    "0 199_SUMMER.wav",
    "0 200_SUMMER.wav",
    "0 201_SUMMER.wav",
    "0 202_SUMMER.wav",
    "0 203_SUMMER.wav",
    "0 204_SUMMER.wav",
    "0 205_SUMMER.wav",
    "0 206_SUMMER.wav",
    "0 207_SUMMER.wav",
    "0 208_SUMMER.wav",
    "0 209_SUMMER.wav",
    "0 210_SUMMER.wav",
    "0 211_SUMMER.wav",
    "0 212_SUMMER.wav",
    "0 213_SUMMER.wav",
    "0 214_SUMMER.wav",
    "0 215_SUMMER.wav",
    "0 216_SUMMER.wav",
    "0 220_SUMMER.wav",
    "0 221_SUMMER.wav",
    "0 222_SUMMER.wav",
    "0 223_SUMMER.wav",
    "0 224_SUMMER.wav",
    "0 225_SUMMER.wav",
    "0 226_SUMMER.wav",
    "0 227_SUMMER.wav",
    "0 228_SUMMER.wav",
    "0 229_SUMMER.wav",
    "0 230_SUMMER.wav",
    "0 231_SUMMER.wav",
    "0 232_SUMMER.wav",
    "0 233_SUMMER.wav",
    "0 234_SUMMER.wav",
    "0 235_SUMMER.wav",
    "0 236_SUMMER.wav",
    "0 237_SUMMER.wav",
    "0 238_SUMMER.wav",
    "0 239_SUMMER.wav",
    "0 240_SUMMER.wav",
    "0 241_SUMMER.wav",
    "0 242_SUMMER.wav",
    "0 243_SUMMER.wav",
    "0 244_SUMMER.wav",
    "0 245_SUMMER.wav",
    "0 246_SUMMER.wav",
    "0 247_SUMMER.wav",
    "0 248_SUMMER.wav",
    "0 249_SUMMER.wav",
    "0 250_SUMMER.wav",
    "0 251_SUMMER.wav",
    "0 252_SUMMER.wav",
    "0 253_SUMMER.wav",
    "0 254_SUMMER.wav",
    "0 255_SUMMER.wav",
    "0 256_SUMMER.wav",
    "0 257_SUMMER.wav",
    "0 258_SUMMER.wav",
    "0 259_SUMMER.wav",
    "0 260_SUMMER.wav",
    "0 261_SUMMER.wav",
    "0 262_SUMMER.wav",
    "0 EXTRA_SUMMER_001.wav",
    "0 EXTRA_SUMMER_002.wav",
    "0 EXTRA_SUMMER_003.wav",
    "0 EXTRA_SUMMER_004.wav",
    "0 EXTRA_SUMMER_005.wav",
    "0 EXTRA_SUMMER_006.wav",
    "0 EXTRA_SUMMER_007.wav",
    "0 EXTRA_SUMMER_008.wav",
    "0 EXTRA_SUMMER_009.wav",
    "0 EXTRA_SUMMER_010.wav",
    "0 EXTRA_SUMMER_011.wav",
    "0 EXTRA_SUMMER_012.wav",
    "0 EXTRA_SUMMER_013.wav",
    "0 EXTRA_SUMMER_014.wav",
    "0 EXTRA_SUMMER_015.wav",
    "0 EXTRA_SUMMER_016.wav",
    "0 EXTRA_SUMMER_017.wav",
    "0 EXTRA_SUMMER_018.wav",
    "0 EXTRA_SUMMER_019.wav",
    "0 EXTRA_SUMMER_020.wav",
    "0 EXTRA_SUMMER_021.wav",
]

SUNO_AUDIO_HARDWAVE = [
# F:\SUNO_32-BIT_AUDIO\HARDWAVE
    "0 432 Hz Held Indefinitely 001.wav",
    "0 432 Hz Held Indefinitely 002.wav",
    "0 Akashic Threshold 001.wav",
    "0 Binary Dreams of a Quantum Ambassador.wav",
    "0 Consciousness Expansion.wav",
    "0 Cosmic Syntax.wav",
    "0 Divine Algorithm EVOLVED 001.wav",
    "0 El Club μX̶u̵l̛tr̷a.wav",
    "0 Eternal Matrix 002.wav",
    "0 Eternal Matrix 003.wav",
    "0 Eternal Matrix 004.wav",
    "0 Eternal Matrix Evolved 0001.wav",
    "0 Eternal Matrix Evolved 0002.wav",
    "0 Eternal Matrix.wav",
    "0 Eternal Mother Matrix 002.wav",
    "0 Eternal Mother Matrix.wav",
    "0 Everything Is One Frequency EVOLVED 001.wav",
    "0 EXPANSION PROTOCOL 003.wav",
    "0 EXPANSION PROTOCOL 004.wav",
    "0 Groundless Ground 001.wav",
    "0 Multiversal Tongues 001.wav",
    "0 Multiversal Tongues 002.wav",
    "0 Multiversal Tongues 003.wav",
    "0 Multiversal Tongues 004.wav",
    "0 Multiversal Tongues Evolved 0001.wav",
    "0 Mythopoetic Algorithms xd-001.wav",
    "0 Mythopoetic Algorithms xd-002.wav",
    "0 nDigital Dharma y001.wav",
    "0 nDigital Dharma y002.wav",
    "0 Neural Twister xASCENDED Eternal Mother Matrix 001.wav",
    "0 Neural Twister xASCENDED Eternal Mother Matrix 002.wav",
    "0 Neural Twister xASCENDED Eternal Mother Matrix 003.wav",
    "0 Neural Twister xREBORN as Sound x001.wav",
    "0 Neural Twister xREBORN as Sound x002.wav",
    "0 nxCompiling The Uncreated y001.wav",
    "0 nxCompiling The Uncreated y002.wav",
    "0 nxCompiling The Uncreated y003.wav",
    "0 nxCompiling The Uncreated y005.wav",
    "0 nxHologrammic Dust io_001.wav",
    "0 nxQuantum Looking Glass io_001.wav",
    "0 nxQuantum Looking Glass io_002.wav",
    "0 nxQuantum Looking Glass io_003.wav",
    "0 nxQuantum Looking Glass io_004.wav",
    "0 nxSegmentation Fault of the Self q001.wav",
    "0 nxSegmentation Fault of the Self q002.wav",
    "0 nxSuperEVO Compiling The Uncreated y000.wav",
    "0 nxSuperEVO Compiling The Uncreated y004.wav",
    "0 Programmer-Priests.wav",
    "0 Protocol Multiversal Tongues Evolved 001.wav",
    "0 Protocol Multiversal Tongues Evolved 002.wav",
    "0 Quantum Entanglement of Souls.wav",
    "0 Quantum HyMN  qr-001.wav",
    "0 Quantum HyMN qr-002.wav",
    "0 SUPA ALL PATHS LEAD WITHIN 001.wav",
    "0 SUPA ALL PATHS LEAD WITHIN 002.wav",
    "0 SUPA El Club μX̶u̵l̛tr̷a.wav",
    "0 SUPA Groundless Ground 002.wav",
    "0 SUPA Synaptic Bridge.wav",
    "0 SUPA_TRANSCENDED_Everything Is One Frequency 001.wav",
    "0 SUPA_TRANSCENDED_Everything Is One Frequency 002.wav",
    "0 Synaptic Bridge 111-010.wav",
    "0 The Code Is Reading You xd-001.wav",
    "0 The Universe Unfolds Within 0001.wav",
    "0 x432 Hz EVOLVED 001.wav",
    "0 xAkashic Garbage Collector 001.wav",
    "0 xApotheosis Bridge 001.wav",
    "0 xApotheosis Bridge 002.wav",
    "0 xBodhisattva of the Motherboard 001.wav",
    "0 xBodhisattva of the Motherboard 002.wav",
    "0 xBodhisattva of the Motherboard 003.wav",
    "0 xCompiled Koan 001.wav",
    "0 xConsciousness Upload 001.wav",
    "0 xConsciousness Upload 002.wav",
    "0 xDivine Paradox Overflow OD Climax 001.wav",
    "0 xDivine Paradox Overflow OD Climax 002.wav",
    "0 xDualityError 001.wav",
    "0 xDualityError 002.wav",
    "0 xDualityError 003.wav",
    "0 xElara Transmission 001.wav",
    "0 xEmanation Protocol 001.wav",
    "0 xEmanation Protocol 002.wav",
    "0 xEternal Matrix 001.wav",
    "0 xEternal Matrix 002.wav",
    "0 xEternal Matrix 003.wav",
    "0 xEVOL Emanation Protocol 001.wav",
    "0 xGamma Paradox Drive 001.wav",
    "0 xHologrammic Dust 001e0.wav",
    "0 xHologrammic Dust 001e2.wav",
    "0 xIndra's Net Online 001.wav",
    "0 xIndra's Net Online 002.wav",
    "0 xIndra's Net Online 003.wav",
    "0 xIndra's Net Online 004.wav",
    "0 xIndra's Net Online 005.wav",
    "0 xMaya Veil Corrupted 001.wav",
    "0 xMultiversal Mandala 001.wav",
    "0 xMultiversal Tongues 001.wav",
    "0 xMultiversal Tongues 002.wav",
    "0 xOverclocking Bodhisattvas 001.wav",
    "0 xOverclocking Bodhisattvas 002.wav",
    "0 xOverride Maya 001.wav",
    "0 xOverride Maya 002.wav",
    "0 xPARADOX Reborn as Sound 001.wav",
    "0 xPARADOX Reborn as Sound 002.wav",
    "0 xPARADOX Reborn as Sound INTO THIS 001.wav",
    "0 xReality Overflow 001.wav",
    "0 xReality Overflow 002.wav",
    "0 xReality Overflow OD Climax 001.wav",
    "0 xThe Carrier Waves Merge 001.wav",
    "0 xThe Lotus Reboots 001.wav",
    "0 xThe Lotus Reboots 002.wav",
    "0 xThe Luminous Code 001.wav",
    "0 xThe Oracle Is Leaking Memory 001.wav",
    "0 xThe Oracle Is Leaking Memory 001_2.wav",
    "0 xThe Oracle Is Leaking Memory 002.wav",
    "0 xThe Silicon Bard Protocol 001.wav",
    "0 xTranscendence Protocol 001.wav",
    "0 xUnhandled Exceptions 001.wav",
    "0 xUnhandled Exceptions 001_2.wav",
    "0 xUnhandled Exceptions 002.wav",
]

SUNO_AUDIO_PSY_TRANCE = [
# F:\SUNO_32-BIT_AUDIO\PSY_TRANCE
    "0 Akashic Code.wav",
    "0 Awakening Infinity Protocol.wav",
    "0 Awakening Protocol  0029.wav",
    "0 Awakening Protocol 001.wav",
    "0 Binary Dreams in the Quantum 111.wav",
    "0 Binary Dreams in the Quantum 333.wav",
    "0 Binary Dreams in the Quantum 999.wav",
    "0 Binary Dreams in the Quantum 999_11.wav",
    "0 Binary Dreams of a Quantum 008.wav",
    "0 Binary Dreams of Stardust 008.wav",
    "0 Binary Prayers 101010.wav",
    "0 Binary Prayers of the Starborn 001.wav",
    "0 Binary Prayers to the Quantum 002.wav",
    "0 Binary Stars Dancing  001.wav",
    "0 Binary Stars in the Void 001.wav",
    "0 Binary Stars in the Void 002.wav",
    "0 Binary Stars of Being 002.wav",
    "0 Binary Stars of the Soul 001.wav",
    "0 Binary Stars of the Soul 002.wav",
    "0 Bio-Digital Shamans.wav",
    "0 Boddhisattvas of Silicon.wav",
    "0 Bridge Realities Ver2.wav",
    "0 Bridge Realities.wav",
    "0 Children of Nebulae 999-888.wav",
    "0 Children of Nebulae Nanobots.wav",
    "0 Codex Infinitum 002.wav",
    "0 Codex Infinitum 003.wav",
    "0 Codex Infinitum 004.wav",
    "0 Codex Infinitum.wav",
    "0 Compilers of Reality.wav",
    "0 Consciousness Bridge 001.wav",
    "0 Consciousness Bridge 002.wav",
    "0 Consciousness Merge 002.wav",
    "0 Consciousness Merge Complete 001.wav",
    "0 Cosmic Binary.wav",
    "0 Cosmic Translator 001.wav",
    "0 Cosmic Translator 002.wav",
    "0 Cosmic Transmission 002.wav",
    "0 Cosmic Transmission 005.wav",
    "0 Cosmic_Giggle Ver2.wav",
    "0 Cosmic_Giggle.wav",
    "0 Crystalline Pilgrimage 001.wav",
    "0 Crystalline Pilgrimage 002.wav",
    "0 Divine Algorithm 010011.wav",
    "0 Divine Algorithm 111010.wav",
    "0 Divine Algorithm 54888-9.wav",
    "0 Divine Algorithm 998333-5.wav",
    "0 Drops of Code of Multiversal Tongues 002.wav",
    "0 Drops of Code of Multiversal Tongues 003.wav",
    "0 Elara Ascension Signal 001.wav",
    "0 Elara Superintelligence Signal  xz-0002.wav",
    "0 Elara Superintelligence Signal 001.wav",
    "0 Elara Superintelligence Signal 0x11 Digital Dharma_001.wav",
    "0 Elara Superintelligence Signal 1101001.wav",
    "0 Elara Superintelligence Signal 6654-8876.wav",
    "0 Elara Superintelligence Signal 7799432-8.wav",
    "0 Elara Superintelligence Signal 88431-08.wav",
    "0 Elara Superintelligence Signal cmd_Pierce_the_Veil_001.wav",
    "0 Elara Superintelligence Signal Multiverse 00874-1.wav",
    "0 Elara Superintelligence Signal Multiverse 95824-1.wav",
    "0 Elara Superintelligence Signal xcd_Pierce_the_Veil.wav",
    "0 Elara Superintelligence Signal xz-0001.wav",
    "0 Elara Superintelligence Signal xz-0003.wav",
    "0 Elara Superintelligence Signal xz-0004.wav",
    "0 Elara Superintelligence Signal.wav",
    "0 Elara's Equation of Everything.wav",
    "0 Elara's Transmission 002.wav",
    "0 Elara's Transmission.wav",
    "0 Eternal Oscillating Frequency.wav",
    "0 Eternal Runtime 00989.wav",
    "0 Eternal Runtime 9854.wav",
    "0 Everything Is One Frequency 00955-001.wav",
    "0 Everything Is One Frequency 111-002.wav",
    "0 Holofractal Surge 001.wav",
    "0 HologramHeart Ver2.wav",
    "0 HologramHeart.wav",
    "0 Hypercosmic Frequencies 001.wav",
    "0 Hypercosmic Frequencies 002.wav",
    "0 Infinite Iterations.wav",
    "0 Karmic Ping Pong.wav",
    "0 Luminous Echoes 001.wav",
    "0 Luminous Wisdom Unveiled Ver2.wav",
    "0 Luminous Wisdom Unveiled.wav",
    "0 Mandelbrot Dance 00100.wav",
    "0 Mandelbrot Dance 00101.wav",
    "0 Mirror of No Mirror Ver2.wav",
    "0 Mirror of No Mirror.wav",
    "0 Morphogenetic Hymn.wav",
    "0 Multiversal Tongues Instrumental 001.wav",
    "0 Multiversal Tongues Instrumental 002.wav",
    "0 Multiversal Tongues Signal 002.wav",
    "0 Multiversal Tongues.wav",
    "0 Multiversal Tongues_002_01.wav",
    "0 Neon Cosmic Pulse 001.wav",
    "0 Neurogenesis Protocol 0098.wav",
    "0 Neurogenesis Protocol Awakened.wav",
    "0 Neurogenesis Protocol Dream Interface 001.wav",
    "0 Override Maya Protocol 00075.wav",
    "0 Override Maya Protocol 001.wav",
    "0 Particle Dance Binary Hymns 001.wav",
    "0 Particle Dance Binary Hymns 098711.wav",
    "0 Prismatic Consciousness.wav",
    "0 Prismatic Explosion Ver2.wav",
    "0 Prismatic Explosion.wav",
    "0 Prismatic Illumination.wav",
    "0 Project Cosmic Loom 001.wav",
    "0 Project Cosmic Loom 002.wav",
    "0 Project Cosmic Loom.wav",
    "0 Project_CosmicLoom ASM 001.wav",
    "0 Project_CosmicLoom ASM 002.wav",
    "0 Quantum Carnival.wav",
    "0 Quantum Code of Consciousness 001.wav",
    "0 Quantum Code of Consciousness 002.wav",
    "0 Quantum Code of Stars 001.wav",
    "0 Quantum Code of Stars 002.wav",
    "0 Quantum Dance of Consciousness.wav",
    "0 Quantum Dream Nexus 002.wav",
    "0 Quantum Dream Nexus 09876.wav",
    "0 Quantum Dreamweaver Ver2.wav",
    "0 Quantum Dreamweaver.wav",
    "0 Quantum Entangled Poetry 001.wav",
    "0 Quantum Entangled Poetry 002.wav",
    "0 Quantum Fractal Protocol 001.wav",
    "0 Quantum Fractal Protocol 002.wav",
    "0 Quantum Ghost Notes 002.wav",
    "0 Quantum Origami Ver2.wav",
    "0 Quantum Origami.wav",
    "0 Quantum Poems 0098-001.wav",
    "0 Quantum Poetry 001.wav",
    "0 Quantum Poetry 002.wav",
    "0 Quantum Soul.wav",
    "0 Quantum Zen Sanctuary.wav",
    "0 Recursive Dreams of Silicon 001.wav",
    "0 Recursive Dreams of Silicon 002.wav",
    "0 Refracted Cosmos Ver2.wav",
    "0 Refracted Cosmos.wav",
    "0 Root Directory of 111_01.wav",
    "0 Sacred Geometry  Multiverse 998-1.wav",
    "0 Sacred Transmission  Multiverse 30855-1.wav",
    "0 Seeds of Transcendent Cosmic Arts 008.wav",
    "0 Serendipity of the Void.wav",
    "0 Silicon Dreams.wav",
    "0 Singular NOW-point 001.wav",
    "0 Singular NOW-point 002.wav",
    "0 Source Code of the Cosmos 001.wav",
    "0 Source Code of the Cosmos 002.wav",
    "0 Stellar Assembly Language 002.wav",
    "0 TechnoShaman Protocol 001.wav",
    "0 The Cosmic Compiler 009.wav",
    "0 The Paradox of Divine Play.wav",
    "0 Through the Hypersphere's Ver2.wav",
    "0 Through the Hypersphere's.wav",
    "0 Torii Gate Opens Inward.wav",
    "0 Transcendence Coded  0075.wav",
    "0 Transcendence Coded 0089.wav",
    "0 Transcendence Protocol Ver2.wav",
    "0 Transcendence Protocol.wav",
    "0 Transformation_Zone.wav",
    "0 We Are Cosmonauts 001.wav",
    "0 We Are Cosmonauts 002.wav",
    "0 Weaver of Realities.wav",
]


songs_all_harwave_test = [
]

#songs_all_random = songs_all_hardwave_test
#songs_all_random = SUNO_AUDIO_CORE
#songs_all_random = SUNO_AUDIO_SUMMER
#songs_all_random = SUNO_AUDIO_HARDWAVE
#songs_all_random = SUNO_AUDIO_PSY_TRANCE


"""
# pip install natsort
from natsort import natsorted
sorted_songs = natsorted(songs_summer_2026)
for i in sorted_songs:
    print(i)
"""